type TAvatars               = "id"|"name"|"createdDate"|"freeze"|"exp"|"silver"|"gold"|"redPowder"|"diamond"|"username"|"missionID"|"magicName"|"gender"|"mainPage"|"subPage"      | ` 'id','name','createdDate','freeze','exp','silver','gold','gender','mainPage','subPage','redPowder','diamond','username','missionID','magicName'                       `
type TUser                  = "id"|"username"|"email"|"firstName"|"lastName"|"birthday"|"registerDate"|"freeze"|"token"                                                        | ` 'id','username','email','firstName','lastName','birthday','registerDate','freeze','token'                                           `
type TRankSetting           = "id"|"startExp"|"hp"|"energy"|"energyEnergy"                                                                                                     | ` 'id','startExp','hp','energy','energyEnergy'                                                                                        `
type TMissions              = "id"|"name"|"description"|"freeze"|"minRank"|"difficulty"|"goal"|"prize"|"monsterID"|"labyrinthsID"                                              | ` 'id','name','description','freeze','minRank','difficulty','goal','prize','monsterID','labyrinthsID'                                 `
type TMonster               = "id"|"name"|"description"|"freeze"|"rankPower"                                                                                                   | ` 'id','name','description','freeze','rankPower'                                                                                      `
type TMaps                  = "id"|"name"|"description"|"freeze"                                                                                                               | ` 'id','name','description','freeze'                                                                                                  `
type TMagics                = "id"|"name"|"description"|"freeze"                                                                                                               | ` 'id','name','description','freeze'                                                                                                  `
type TLabyrinths            = "id"|"name"|"description"|"freeze"|"data"|"mapID"                                                                                                | ` 'id','name','description','freeze','data','mapID'                                                                                   `
type TItems                 = 'id'|'name'|'description'|'freeze'|'price'|'sale'|'color' |'upgrade'|'rank'|'categoryItem' |'magicName'|"minAvatarRank" |"maxUpgrade"             | ` 'id','name','description','freeze','price','sale','color' ,'upgrade','rank','categoryItem' ,'magicName','minAvatarRank' ,'maxUpgrade'`
type TCategoriesItems       = "id"|"name"|"description"|"freeze"                                                                                                               | ` 'id','name','description','freeze'                                                                                                  `
type TCards                 = "id"|"name"|"description"|"type"|"price"|"move"|"attack"|"upgrade"|"delay"|"magicName"|"freeze"|"minAvatarRank"|"maxUpgrade"                      | ` 'id','name','description','type','price','move','attack','upgrade','delay','magicName','freeze','minAvatarRank','maxUpgrade'         `
type TAvatarsMonsters       = "id"|"avatarLog"|"monsterLog"|"avatarID"|"itemID"                                                                                                | ` 'id','avatarLog','monsterLog','avatarID','itemID'                                                                                   `
type TAvatarsLabyrinths     = "id"|"labyrinthData"|"activeMissionID"|"labyrinthID"                                                                                             | ` 'id','labyrinthData','activeMissionID','labyrinthID'                                                                                `
type TAvatarsItems          = "id"|"active"|"rank"|"avatarID"|"itemID"                                                                                                         | ` 'id','active','rank','avatarID','itemID'                                                                                            `
type TAvatarsCard           = "id"|"rank"|"avatarID"|"cardID"                                                                                                                  | ` 'id','rank','avatarID','cardID'                                                                                                     `
type TUpgrade               = 'leven1'|'leven2'|'leven3'|'leven4'|'leven5'|'leven6'                                                                                            | ` 'leven1','leven2','leven3','leven4','leven5','leven6'                                                                               `
type TGlobalSetting         = "gameName"|"description"|"enablePvp"|"avatarPerUser"|"maxUpgrade"                                                                                | ` 'gameName','description','enablePvp','avatarPerUser','maxUpgrade'                                                                   `







